# Generated by Django 3.2.4 on 2022-04-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField()),
                ('date_last_edited', models.DateField(auto_now=True)),
                ('post_type', models.CharField(choices=[('announcement', 'Announcement'), ('recipe', 'Recipe'), ('personal_article', 'Personal Article'), ('diy', 'DIY')], max_length=100)),
            ],
        ),
    ]
