# Generated by Django 3.2.4 on 2022-06-16 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220615_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_last_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
