# Generated by Django 3.2.4 on 2022-06-16 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_date_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_last_edited',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 19, 7, 15, 821133)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 19, 7, 15, 821078)),
        ),
    ]
