# Generated by Django 3.2.4 on 2022-06-21 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220615_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.post')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('recipe', 'Recipe'), ('article', 'Article')], max_length=100),
        ),
    ]
