# Generated by Django 4.0.6 on 2022-07-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='approved_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
