# Generated by Django 3.2.4 on 2022-06-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_amount_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(max_length=3),
        ),
    ]
