# Generated by Django 3.2.4 on 2022-06-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220608_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_of_measurement',
            field=models.CharField(default='lb', max_length=10),
            preserve_default=False,
        ),
    ]
